"""Place-Time Brief Builder — build the key grounding document."""

from pathlib import Path
from typing import Optional


def build_markdown(audio_file: str, recording_time: Optional[str],
                   duration_sec: float, location: Optional[str],
                   lat: Optional[float], lon: Optional[float],
                   sound_cues: list[str],
                   story_time_input: str, resolved_label: str,
                   start_year: int, end_year: int,
                   nearby_entities: list[dict],
                   period_context: list[dict],
                   uncertainties: list[str],
                   suggested_atmosphere: Optional[str] = None) -> str:
    """Build the Place-Time Brief as a markdown document."""

    cues_str = '\n'.join(f'- {c}' for c in sound_cues) if sound_cues else '- (none provided)'

    entities_str = ''
    if nearby_entities:
        for e in nearby_entities:
            entities_str += f"\n### {e.get('name', 'Unknown')}\n"
            entities_str += f"- Type: {e.get('type', 'unknown')}\n"
            entities_str += f"- Source: {e.get('source', 'unknown')}\n"
            entities_str += f"- Summary: {e.get('summary', '')}\n"
    else:
        entities_str = '\n*(pending retrieval)*\n'

    period_str = ''
    if period_context:
        for p in period_context:
            period_str += f"- {p.get('claim', '')} (source: {p.get('source', 'unknown')})\n"
    else:
        period_str = '*(pending retrieval)*\n'

    uncertain_str = '\n'.join(f'- {u}' for u in uncertainties) if uncertainties else '- (pending retrieval)'

    coord_str = f"{lat}, {lon}" if lat is not None and lon is not None else "N/A"

    return f"""# Place-Time Brief

## Recording Anchor
- Audio file: {audio_file}
- Recording time: {recording_time or 'N/A'}
- Duration: {duration_sec:.1f}s
- Location: {location or 'N/A'}
- Coordinates: {coord_str}
- Sound cues:
{cues_str}

## Story Time
- User input: {story_time_input}
- Resolved period: {resolved_label}
- Search range: {start_year}–{end_year}

## Retrieved Place Context
### Nearby Places
{entities_str}
### Geography
*(see nearby places for geographic context)*

### Historical Background
{period_str}
### Cultural / Urban Context
*(integrated with historical background above)*

### Sources
*(see individual entity sources above)*

## Usable Story Materials
The story may safely use:
- Geographic features associated with {location or 'the location'}
- Historical context from {start_year}–{end_year}

## Uncertain or Missing Context
The system did not verify:
{uncertain_str}

## Fiction Boundary
The story may invent fictional characters and scenes,
but it should not invent factual events, real people, or local history.

## Suggested Atmosphere
- Mood: {suggested_atmosphere or '(to be determined)'}
- Possible narrator: (to be determined)
- Sonic motifs: {', '.join(sound_cues) if sound_cues else '(to be determined)'}
- Story scale: intimate / personal

---
*This brief was auto-generated by Geo-Sonic Story. Facts are retrieved; stories are imagined.*
"""


def save_brief(markdown: str, output_path: str):
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding='utf-8')
