"""Story Seed Generator — generate fictional story seed candidates.

In the MVP, seeds are generated by the agent (Cola) and serialized here.
The module provides the data structures and save/load utilities.
"""

import json
from pathlib import Path
from typing import Optional


class StorySeed:
    def __init__(self, seed_id: str, title: str, mode: str,
                 summary: str,
                 uses_retrieved_context: list[str],
                 fictional_elements: list[str],
                 risk_notes: list[str],
                 audio_dependency: Optional[dict] = None):
        self.seed_id = seed_id
        self.title = title
        self.mode = mode
        self.summary = summary
        self.uses_retrieved_context = uses_retrieved_context
        self.fictional_elements = fictional_elements
        self.risk_notes = risk_notes
        self.audio_dependency = audio_dependency or {}

    def to_dict(self) -> dict:
        d = {
            "id": self.seed_id,
            "title": self.title,
            "mode": self.mode,
            "summary": self.summary,
            "uses_retrieved_context": self.uses_retrieved_context,
            "fictional_elements": self.fictional_elements,
            "risk_notes": self.risk_notes,
        }
        if self.audio_dependency:
            d["audio_dependency"] = self.audio_dependency
        return d


class SeedCollection:
    def __init__(self, seeds: list[StorySeed]):
        self.seeds = seeds

    def to_dict(self) -> dict:
        return {"seeds": [s.to_dict() for s in self.seeds]}

    def save(self, output_path: str):
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self.to_dict(), indent=2, ensure_ascii=False))


def create_empty_collection() -> SeedCollection:
    return SeedCollection(seeds=[])


def add_seed(collection: SeedCollection, seed: StorySeed) -> SeedCollection:
    collection.seeds.append(seed)
    return collection
